application: mail-safe-test
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

handlers:
- url: .*
  script: run.mail_safe_test.app
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^tests/(.*/)?$

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
